In [1]:
import numpy as np 
import pandas as pd

In [4]:
data = pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns = ['day'],inplace = True)

In [5]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [6]:
# p(yes)
# p(no)

In [7]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
py = 9/14
pn = 5/14

In [10]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [11]:
#outlook
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [12]:
pon = 0
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [15]:
#temp
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [16]:
pcooln = 1/5
photn= 2/5
pmildn=2/5

pcooly = 3/9
photy = 2/9
pmildy = 4/9

In [17]:
#humidity
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [18]:
phighno = 4/5
pnormalno = 1/5

phighy = 3/9
pnormaly = 6/9

In [19]:
# wind
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [20]:
pstrongn = 3/5
pweakn = 2/5

pstrongy = 3/9
pweaky = 6/9

In [21]:
#outlook = sunny, temp = hot, humidity = high, wind = weak
pyes = py*psy*photy*phighy*pweaky 
print(pyes)

0.007054673721340388

In [22]:
pno = pn*psn*photn*phighno*pweakn
print(pno)

0.02742857142857143